name: Generate Swagger JSON

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Swagger JSON
        run: mkdir -p ./swagger && yarn swagger:generate

      - name: Push swagger documentation to Compass
        run: |
          curl -X PUT https://eficodeadvisory.atlassian.net/gateway/api/compass/v1/component/72d1745c-7ad9-474d-ad57-872b84eb96eb/app/564688a0-afba-45d3-b882-dbf6edbe6066/attachment/swagger-json -F file=@./swagger/swagger.json --user "${{secrets.COMPASS_USER}}:${{secrets.COMPASS_TOKEN}}"
